### ISSUE TITLE
Bug: Search mode should use cHash

### ISSUE THREAD

**Issue by christianbltr** [in2code-de/in2contact#1]
When I use the inbuild search, I get an error

```
Page Not Found
Reason: Request parameters could not be validated (&cHash empty)

```

Seen on TYPO3-Version 8.7.8

Expected:
The search is executed and I see the matching persons.

![auswahl_051](https://user-images.githubusercontent.com/11410553/33994396-a1d47ea2-e0da-11e7-868d-4c1b664ca18b.png)

![auswahl_052](https://user-images.githubusercontent.com/11410553/33994411-acea5082-e0da-11e7-8013-b772e9f5c7d2.png)

**Comment by einpraegsam** [comment]
Thx for the hint. I pushed a fix to develop branch.
