### ISSUE TITLE
Feature: Select single persons

### ISSUE THREAD

**Issue by christianbltr** [in2code-de/in2contact#2]
As an editor I want to be able to select single persons, because I want to display the resonsible persons for that topic the current page is about.

*More Information*
Curruntly only a full list of persons can be shown in the frontend. The list can be filtered in the frontend via search (see #1), but not in the backend. It would be greate to select one or more person records which then will be displayed solely in the frontend on that page the editor is currently working on.

**Comment by einpraegsam** [comment]
Yes, the view for showing a single person is still missing.
Do you want to sponsor it?

**Comment by einpraegsam** [comment]
I think we would need 8h to resolve this feature
