### ISSUE TITLE
Feature: Select category of persons

### ISSUE THREAD

**Issue by christianbltr** [in2code-de/in2contact#3]
As an editor I want to be able to select a category of persons, because I want to display all the persons which belong to a given department.

*More Information*
Currently only a full list of persons can be shown in the frontend. The list can be filtered in the frontend via search (see #1), but not in the backend. It would be greate to select a category from which persons will be displayed, so that if a person is added to a category or deleted from a category, the list of persons will automatically updated.

Addtionally it would be greate to combine categories with AND or OR (as implemented in the news extension). But this may also be an addtional story.

**Comment by einpraegsam** [comment]
Yes it's true that this is a missing feature. There is not categorization at the moment. Are you willing to sponsor it?

**Comment by einpraegsam** [comment]
1) Adding a category filter in plugin would need 5h
2) Adding another field in plugin which combines categories with AND or OR would need another 3h
